version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask_app
    restart: always
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8200
    ports:
      - "8200:8200"
    networks:
      - keycloak_shared_network  # Use the same network as Keycloak
    volumes:
      - .:/app

networks:
  keycloak_shared_network:
    external: true  # Connects to the existing Keycloak network

